### ISSUE TITLE
BME280 data

### ISSUE THREAD

**Issue by bipsendk** [lichtteil/local_luftdaten#1]
Unfortunately I see an issue when using an BME280 sensor..

The output:

{"software_version": "NRZ-2018-123B", "age":"35", "sensordatavalues":[{"value_type":"SDS_P1","value":"0.55"},{"value_type":"SDS_P2","value":"0.55"},{"value_type":"BME280_temperature","value":"23.36"},{"value_type":"BME280_humidity","value":"49.53"},{"value_type":"BME280_pressure","value":"103342.53"},{"value_type":"samples","value":"1730201"},{"value_type":"min_micro","value":"81"},{"value_type":"max_micro","value":"21159"},{"value_type":"signal","value":"-63"}]}

**Comment by vtashev** [comment]
I have fixed that for myself and created pull request
you can see here https://github.com/vtashev/local_luftdaten/commit/65201ddac439a1b46325743dbb131dbf46ad1308

**Comment by lichtteil** [comment]
Thanks for the sample output. Looks like default DHT22 renders value type `temperature` but BME280 has for some reason value type `BME280_temperature`.

**Comment by lichtteil** [comment]
I added BME280 values, you can define them in you config:
```
monitored_conditions:
  - BME280_temperature
  - BME280_humidity
  - BME280_pressure
```

Let me know if it works.

**Comment by lichtteil** [comment]
I just replaced my DHT22 (which had always 99% humidity) with the BME280 and it works fine. For air pressure I use this template sensor:
```
air_pressure:
  value_template: '{{ (states("sensor.feinstaubsensor_pressure") | float / 100) | round(1) }}'
  friendly_name: 'Luftdruck'
  unit_of_measurement: 'hPa'
```
