### ISSUE TITLE
Settings for BME280/ESP8266 from omebridge-mcuiot

### ISSUE THREAD

**Issue by NoTrace-Kai** [lichtteil/local_luftdaten#19]
Hallo,
perhaps you can help me with the settings for that web-output?

`{ "Hostname": "NODE-177D3F", "Model": "BME", "Version": "1.5", "Firmware": "2.2.0", "Data": {"Temperature": 20.495327102804, "Humidity": 49.896, "Moisture": 4, "Status": 0, "Barometer": 1036.238, "Barometer Locl": 997.523, "Dew": 11.01 }}`

So it won't work:
`sensor:
- platform: local_luftdaten
host: 192.168.2.155
name: Temp-SZ
monitored_conditions:
- Temperature
- Humidity
- Barometer`

That is the Info from the HA-Log:
`Invalid config for [sensor.local_luftdaten]: value is not allowed @ data['monitored_conditions'][0]. Got 'Temperature' value is not allowed @ data['monitored_conditions'][1]. Got 'Humidity' value is not allowed @ data['monitored_conditions'][2]. Got 'Barometer'. (See ?, line ?).`

I am using some ESP8266 with BME280 in my Homebridge (mcuiot PlugIn) and want the data also in my HomeAssistant.
Thanks for a little help ...
CU Kai

**Comment by lichtteil** [comment]
Hi Kai,
this custom integration is tailored to the [Luftdaten Sensor Firmware](https://luftdaten.info/feinstaubsensor-bauen/).

Please have a look at the Rest Sensor here: https://www.home-assistant.io/integrations/rest/
Maybe you can use something like:
```
sensor:
  - platform: rest
    resource: http://192.168.2.155
    name: Temp-SZ
    value_template: '{{ value_json.Data.Temperature | round(1) }}'
    unit_of_measurement: "°C"
```

You need to define multiple sensors for each reading (temperature, humidity, ...).

Cheers
Mario
