### ISSUE TITLE
no datas in Home App

### ISSUE THREAD

**Issue by wdylag** [lichtteil/local_luftdaten#22]
I use this integration with Home Assistant for PM, humidity and temperature sensors but no idea why the only temperature is visible in my Home App on iPhone. The HA App show all these datas so how can I move the datas to Home App?

**Comment by lichtteil** [comment]
Sorry, I have no iPhone and don't know what exactly the Home App is. Are you maybe using the HomeKit integration? Can you give me some more details?
In case all the sensors show up in Home-Assistant then I guess the problem is in some other component, not this one.

**Comment by wdylag** [comment]
Home App is the official app for Homekit on iPhone :) so I need to put the sensor results to the Homekit

**Comment by lichtteil** [comment]
Did you read the documentation here? https://www.home-assistant.io/integrations/homekit/
Maybe you have to add the sensors to your `filter` settings?

**Comment by Joe3n** [comment]
@lichtteil This should be closed. This has nothing to do with this integration and a configuration issue of the HomeKit integration. I use HomeKit and local_luftdaten values are shown in HomeKit

**configuration.yaml**
```
homekit:
  - filter:
      include_entities:
        - sensor.airdata_pm25
        - sensor.airdata_temperature
        - sensor.airdata_humidity
```
